"""
AI response data models.

Defines structured outputs from AI agents. These models are open source
and provide the interface contract between the AI layer and downstream
consumers (QGIS plugin, web dashboards, CAD integrations).

The optimized prompt templates and hosted LLM infrastructure that produce
these responses are part of the commercial NatureOS Cloud platform.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Confidence(str, Enum):
    """AI response confidence level."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNCERTAIN = "uncertain"


class RecommendationType(str, Enum):
    """Type of ecological recommendation."""
    SPECIES_SELECTION = "species_selection"
    IRRIGATION_STRATEGY = "irrigation_strategy"
    HABITAT_RESTORATION = "habitat_restoration"
    HEAT_MITIGATION = "heat_mitigation"
    BIODIVERSITY_ENHANCEMENT = "biodiversity_enhancement"
    CARBON_OPTIMIZATION = "carbon_optimization"
    GENERAL_ADVICE = "general_advice"


@dataclass
class AIResponse:
    """
    Standardized response from any NatureOS AI agent.

    Attributes
    ----------
    agent_name : str
        Which agent produced this response
    query_summary : str
        Brief summary of what was asked
    response_text : str
        Human-readable response
    confidence : Confidence
        Agent's confidence in the response
    references : list[str]
        Scientific or institutional references cited
    engine_results : dict
        Structured results from computational engines that informed this response
    disclaimer : str
        Standard disclaimer about AI-assisted ecological advice
    """

    agent_name: str
    query_summary: str
    response_text: str
    confidence: Confidence = Confidence.MEDIUM
    references: list[str] = field(default_factory=list)
    engine_results: dict = field(default_factory=dict)
    disclaimer: str = (
        "This recommendation was generated by NatureOS AI and should be "
        "reviewed by a qualified ecologist or landscape architect before "
        "implementation. Computational engines provide deterministic analysis; "
        "AI interpretation adds reasoning but does not replace professional judgment."
    )

    def summary(self) -> str:
        return (
            f"[{self.agent_name}] {self.query_summary}\n"
            f"Confidence: {self.confidence.value}\n"
            f"───\n"
            f"{self.response_text}\n"
            f"───\n"
            f"{self.disclaimer}"
        )


@dataclass
class DesignRecommendation:
    """
    A specific design recommendation generated by an AI agent.

    Attributes
    ----------
    recommendation_type : RecommendationType
        Category of recommendation
    title : str
        Short title for the recommendation
    description : str
        Detailed explanation
    species_suggestions : list[str]
        Scientific names of recommended species
    rationale : str
        Ecological reasoning behind the recommendation
    confidence : Confidence
        Agent's confidence in this specific recommendation
    alternative_options : list[str]
        Alternative approaches if applicable
    """

    recommendation_type: RecommendationType
    title: str
    description: str
    species_suggestions: list[str] = field(default_factory=list)
    rationale: str = ""
    confidence: Confidence = Confidence.MEDIUM
    alternative_options: list[str] = field(default_factory=list)
